apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: mariadb
  labels:
    app: mariadb
spec:
  # Choose how to expose your service
  type: LoadBalancer
  loadBalancerIP: 192.168.2.129
  ports:
    # The port number to expose the service
    - port: 3306
  # Pod to route service traffic  
  selector:
    app: mariadb
